version: '3'
services:
  shop:
    image: shabushabu/javashop.shop:latest
    build:
      ./shop
    ports:
      - "8010:8010"
      - "8000:8000"
    links:
      - products
      - stock
      - instruments
      - conductors
    environment:
      - OTEL_COLLECTOR=${OTEL_COLLECTOR}
      - USERNAME=${SHOP_USER}
      - TOKEN=${SPLUNK_ACCESS_TOKEN}
      - REALM=${SPLUNK_REALM}
    healthcheck:
      test: curl -sS http://localhost:8010/healthcheck | grep -c 200 > /dev/null
      interval: 2s
      retries: 15
      start_period: 5s
      timeout: 2s
    depends_on:
      instruments:
        condition: service_healthy
      conductors:
        condition: service_healthy
  products:
    image: shabushabu/javashop.products:latest
    build:
      ./products
    ports:
      - "8020:8020"
      - "8001:8001"
    healthcheck:
      test: curl -sS http://localhost:8020/products/healthcheck | grep -c 200 > /dev/null
      interval: 2s
      retries: 5
      start_period: 5s
      timeout: 2s
    environment:
      - OTEL_COLLECTOR=${OTEL_COLLECTOR}
      - USERNAME=${SHOP_USER}
      - TOKEN=${SPLUNK_ACCESS_TOKEN}
      - REALM=${SPLUNK_REALM}
  stock:
    image: shabushabu/javashop.stock:latest
    build:
      ./stock
    ports:
      - "8030:8030"
      - "8002:8002"
    healthcheck:
      test: curl -sS http://localhost:8030/healthcheck | grep -c 200 > /dev/null
      interval: 2s
      retries: 5
      start_period: 5s
      timeout: 2s 
    environment:
      - OTEL_COLLECTOR=${OTEL_COLLECTOR}
      - USERNAME=${SHOP_USER}
      - TOKEN=${SPLUNK_ACCESS_TOKEN}
      - REALM=${SPLUNK_REALM}
  shoptester:
    image: shabushabu/javashop.tester:latest
    build:
      ./test
    links:
      - shop
    environment:
      - OTEL_COLLECTOR=${OTEL_COLLECTOR}
      - USERNAME=${SHOP_USER}
      - TOKEN=${SPLUNK_ACCESS_TOKEN}
      - REALM=${SPLUNK_REALM}
    depends_on:  
      shop:
        condition: service_healthy 
  instruments:
    image:  shabushabu/javashop.instruments:latest
    build:
      ./instruments
    ports:
      - "8040:8040"
      - "8003:8003"
    healthcheck:
      test: curl -sS http://localhost:8040/healthcheck | grep -c 200 > /dev/null
      #curl --fail http://localhost:8040//healthcheck  || exit 1
      interval: 2s
      retries: 45
      start_period: 45s
      timeout: 2s
    links:
      - postgresDB
    environment:
      - OTEL_COLLECTOR=${OTEL_COLLECTOR}
      - USERNAME=${SHOP_USER}
      - TOKEN=${SPLUNK_ACCESS_TOKEN}
      - REALM=${SPLUNK_REALM}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresDB:5432/instruments
      - SPRING_DATASOURCE_USERNAME=instruments
      - SPRING_DATASOURCE_PASSWORD=instruments
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    depends_on:
      postgresDB:
        condition: service_healthy
  conductors:
    image:  shabushabu/javashop.conductors:latest
    build:
      ./conductors
    ports:
      - "8044:8044"
      - "8004:8004"
    healthcheck:
      test: curl -sS http://localhost:8044/healthcheck | grep -c 200 > /dev/null
      #curl --fail http://localhost:8040//healthcheck  || exit 1
      interval: 2s
      retries: 45
      start_period: 25s
      timeout: 2s
    links:
      - conductorsDB
    environment:
      - OTEL_COLLECTOR=${OTEL_COLLECTOR}
      - USERNAME=${SHOP_USER}
      - TOKEN=${SPLUNK_ACCESS_TOKEN}
      - REALM=${SPLUNK_REALM}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://conductorsDB:5433/conductors
      - SPRING_DATASOURCE_USERNAME=conductors
      - SPRING_DATASOURCE_PASSWORD=conductors
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - PGUSER=conductors
    depends_on:
      conductorsDB:
        condition: service_healthy
  postgresDB:
    image: "postgres:13.1-alpine"
    container_name: postgresDB
#    restart: always
    environment:
      - POSTGRES_USER=instruments
      - POSTGRES_PASSWORD=instruments
      - PGUSER=instruments 
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 2s
      start_period: 35s
      retries: 50
    volumes:
      - ./db/sql/instruments-latest.sql:/docker-entrypoint-initdb.d/instruments-latest.sql
      - ./db/sql/instruments-chicago.sql:/docker-entrypoint-initdb.d/instruments-chicago.sql
      - ./db/sql/instruments-oregon.sql:/docker-entrypoint-initdb.d/instruments-oregon.sql
      #- ./db/sql/instruments-conductors.sql:/docker-entrypoint-initdb.d/instruments-conductors.sql
      - ./db/sql/instruments-us-east.sql:/docker-entrypoint-initdb.d/instruments-us-east.sql
      - ./db/sql/instruments-us-west.sql:/docker-entrypoint-initdb.d/instruments-us-west.sql
      #- ./db/sql/instruments-us-south.sql:/docker-entrypoint-initdb.d/instruments-us-south.sql
      - ./db/sql/instruments-us-central.sql:/docker-entrypoint-initdb.d/instruments-us-central.sql
      
  conductorsDB:
    image: "postgres:13.1-alpine"
    container_name: conductorsDB
#    restart: always
    environment:
      - POSTGRES_USER=conductors
      - POSTGRES_PASSWORD=conductors
      - PGUSER=conductors
      - PGPORT=5433
    ports:
      - "5433:5433"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 2s
      start_period: 20s
      retries: 50
    volumes:
      - ./db2/sql/instruments-latest.sql:/docker-entrypoint-initdb.d/instruments-latest.sql
      - ./db2/sql/instruments-conductors-japan-gold.sql:/docker-entrypoint-initdb.d/instruments-conductors-japan-gold.sql
      - ./db2/sql/instruments-conductors-canada-gold.sql:/docker-entrypoint-initdb.d/instruments-conductors-canada-gold.sql
      - ./db2/sql/instruments-conductors-italy-gold.sql:/docker-entrypoint-initdb.d/instruments-conductors-italy-gold.sql
      - ./db2/sql/instruments-conductors-us-silver.sql:/docker-entrypoint-initdb.d/instruments-conductors-us-silver.sql
      - ./db2/sql/instruments-conductors-japan-silver.sql:/docker-entrypoint-initdb.d/instruments-conductors-japan-silver.sql
      - ./db2/sql/instruments-conductors-canada-silver.sql:/docker-entrypoint-initdb.d/instruments-conductors-canada-silver.sql
      - ./db2/sql/instruments-conductors-italy-silver.sql:/docker-entrypoint-initdb.d/instruments-conductors-italy-silver.sql
      - ./db2/sql/instruments-conductors-us-platinum.sql:/docker-entrypoint-initdb.d/instruments-conductors-us-platinum.sql
      - ./db2/sql/instruments-conductors-japan-platinum.sql:/docker-entrypoint-initdb.d/instruments-conductors-japan-platinum.sql
      - ./db2/sql/instruments-conductors-canada-platinum.sql:/docker-entrypoint-initdb.d/instruments-conductors-canada-platinum.sql
      - ./db2/sql/instruments-conductors-italy-platinum.sql:/docker-entrypoint-initdb.d/instruments-conductors-italy-platinum.sql
      - ./db2/sql/instruments-conductors-us.sql:/docker-entrypoint-initdb.d/instruments-conductors-us.sql
      - ./db2/sql/instruments-conductors-japan.sql:/docker-entrypoint-initdb.d/instruments-conductors-japan.sql
      - ./db2/sql/instruments-conductors-canada.sql:/docker-entrypoint-initdb.d/instruments-conductors-canada.sql
      - ./db2/sql/instruments-conductors-italy.sql:/docker-entrypoint-initdb.d/instruments-conductors-italy.sql
     
     
